### ISSUE TITLE
Consider panels as part of the desktop

### ISSUE THREAD

**Issue by kupiqu** [tcorreabr/Parachute#1]
There is a "glitch" with panels when moving from desktop to desktop, i.e. panels transiently appear in the desktop transition and then disappear becase they are not considered part of the desktop in this script.

It would be great if panels would be considered part of the desktop like widgets. If that would be the case panels would always be present and the transient glitch would be gone.

**Comment by tcorreabr** [comment]
I don't know why but in Kwin scripts the main window must always be on top. Thus, it would be complicated to reserve space for the panels. So I thought the script should occupy the entire screen and ignore the panels.

Are you using the "Slide" animation type? Could you switch to "Desktop Cube Animation" and see if the problem persists?

**Comment by kupiqu** [comment]
This only happens with the "Slide" animation, which is unfortunately the one I use.

Fading and Cube animations are not affected. Cube animation has an option to ignore panels or not, but neither case causes any glitch.

**Comment by tcorreabr** [comment]
I've put a note on README.md to warn the user about this.

**Comment by cupnoodles14** [comment]
Enabling "Slide docks" in desktop effect settings seems to fix the issue too.

**Comment by kupiqu** [comment]
> Enabling "Slide docks" in desktop effect settings seems to fix the issue too.

I know, but it looks ugly to my eyes when using it outside Parachute

**Comment by ryu-ketsueki** [comment]
I found something curious about this with Latte dock. I think it's because how the Show Desktop effect also hides panels but if Latte's panels are set as Windows Can Cover or a similar one, they don't show up at all when switching desktops. But a fun one is certainly the dock itself. I enabled the "Can be above fullscreen windows" option for docks and it now makes Parachute looks like GNOME Overview (and I love it!). Makes me wish Parachute had some kind of apps grid to complete the package. It's awesome. And the dock still launches apps in this mode (was crashing before but now it works perfectly without crashes or bugs).
![Flameshot_202101 8_185118](https://user-images.githubusercontent.com/39316730/104067798-976e9e80-51e2-11eb-8ef1-3dc9982c84c5.png)

**Comment by koma111** [comment]
> ![Flameshot_202101 8_185118](https://user-images.githubusercontent.com/39316730/104067798-976e9e80-51e2-11eb-8ef1-3dc9982c84c5.png)

A few questions, unrelated to the issue, but related to this screenshot that I find weird:
1. How did you get Konsole (and presumably other apps too, to use CSD on KDE? What kind of sorcery is this? I would like to know.
2. What is up with the last virtual desktop? How did you get a different wallpaper on it?
3. Which Parachute version are you using? Isn't there supposed to be '+' and '-' buttons on each side of the virtual desktop array, to add and remove desktops?

**Comment by ryu-ketsueki** [comment]
> A few questions, unrelated to the issue, but related to this screenshot that I find weird:
> 
>     1. How did you get Konsole (and presumably other apps too, to use CSD on KDE? What kind of sorcery is this? I would like to know.
> 
>     2. What is up with the last virtual desktop? How did you get a different wallpaper on it?
> 
>     3. Which Parachute version are you using? Isn't there supposed to be '+' and '-' buttons on each side of the virtual desktop array, to add and remove desktops?

Let's go by parts:

1. That's actually a big fat trick. It's not CSD but actually the toolbar with Close Session button on the right and a Window-Specific Override to not show the titlebar for the main window. Maximize and Minimize are actually only Find Next and Find Previous. I *wish* I was that good of a programmer to bring a Headerbar to some KDE Apps. Philosophies aside, a smart use of Headerbars can actually make the app look interesting. And that screenshot doesn't show it but I am using a Global Menu on top. Here:
![Flameshot_20210111_120833](https://user-images.githubusercontent.com/39316730/104199103-c9137f80-5405-11eb-8c42-fea0f6716ac1.png)
2. It's a bug on Parachute. I changed wallpaper and it didn't update on that last virtual desktop. But it's not something frequent. Sometimes it happens, sometimes it doesn't and can be on any of the virtual desktops. I think there is a point parachute simply stops checking if the wallpaper updated or not.
3. Those only appear when I hover the mouse over the virtual desktops on the top for me, which I kinda prefer it that way. Not sure if it's intended but at least keeps it clean.

**Comment by koma111** [comment]
Oh ok, you got me with the first one, I almost burst out laughing
I honestly think that there should be an option to have 2 top bars instead of 3. If there is a menubar, the window buttons should be in the menubar. If there is no menubar, just the toolbar, the buttons could be in the toolbar.

As for the second, it is probably best to open that as a new issue
For the third, my bad, yes, that is correct 0.9.1 behavior. They were always shown in previous versions.
