### ISSUE TITLE
Issue with latte dock

### ISSUE THREAD

**Issue by alexjp** [tcorreabr/Parachute#31]
Hi,

Currently Parachute seems to have an issue with Latte-dock, sometimes it shows, sometimes doesn't, sometimes it flickers.

Could there be made an option to either hide or show latte-dock ? ( normally i guess it should be hidden, but i would actually like for it to show ...then i would have a app launcher and activity changer on Parachute :P )

Thanks !

**Comment by tcorreabr** [comment]
> Currently Parachute seems to have an issue with Latte-dock, sometimes it shows, sometimes doesn't, sometimes it flickers.

During the development of Parachute flickers appeared and disappeared a few times, but I never thought they were related to the use along with latte. I hope you're right because it would be a first step to solve the problem.
 
> Could there be made an option to either hide or show latte-dock ? ( normally i guess it should be hidden, but i would actually like for it to show ...then i would have a app launcher and activity changer on Parachute :P )

I thought it would be cool to have an option to leave the panels visible when Parachute is activated, but unfortunately the windows created by KWin scripts are necessarily "always on top" type.

**Comment by tcorreabr** [comment]
Also, please read issue #1. Maybe it will solve your problem with the latte panel appearing and disappearing.
