### ISSUE TITLE
Type to invoke Krunner?

### ISSUE THREAD

**Issue by ripefig** [tcorreabr/Parachute#43]
Seems like this addition would fully reproduce Gnome Overview (if less than elegantly)

**Comment by koma111** [comment]
Maybe a small text could be added like "type to search" which would be consistent with Plasma's built-in App Dashboard (the fullscreen menu)

**Comment by keeganmilsten** [comment]
I love this idea! Parachute has already made my workflow so much more efficient, but sneaking Krunner in there as well would complete this perfectly. Additionally, I suspect adding Krunner would bring this project much more attention due to all those people out there who like parts of GNOME but prefer KDE Plasma, or are just switching to Plasma for the first time.

Thank you so much @tcorreabr for crafting such an elegant and amazing addition to Plasma, I thoroughly love this project!

**Comment by tcorreabr** [comment]
> Maybe a small text could be added like "type to search" which would be consistent with Plasma's built-in App Dashboard (the fullscreen menu)

Yes, this would be the way to go.

**Comment by tcorreabr** [comment]
> I love this idea! Parachute has already made my workflow so much more efficient, but sneaking Krunner in there as well would complete this perfectly. Additionally, I suspect adding Krunner would bring this project much more attention due to all those people out there who like parts of GNOME but prefer KDE Plasma, or are just switching to Plasma for the first time.
> 
> Thank you so much @tcorreabr for crafting such an elegant and amazing addition to Plasma, I thoroughly love this project!

Thanks! I appreciate your words.

**Comment by Eoin-ONeill-Yokai** [comment]
KRunner integration would be a dreamsend. I would probably use this to replace my start-menu launcher entirely to make it more gnome esque.

**Comment by ikeofkc** [comment]
I could leave GNOME finally if this was implemented. Sadly the gnome activities workflow is not reproducible in other DEs. This could be amazing.

**Comment by AtifChy** [comment]
You guys too much used to gnome. you can call krunner after anywhere in kde but still want it to appear on parachute.

**Comment by 20manas** [comment]
Wouldn't it be better to invoke Krunner by pressing a key such as `r` so that other keys can be used for other shortcuts such as filtering windows by pressing `f` or using `hjkl` for navigating through windows?

**Comment by tcorreabr** [comment]
My idea is to reproduce Plasma's fullscreen launcher behavior: arrow keys for navigation and alphabet keys to activate krunner search.

**Comment by ikeofkc** [comment]
sounds like you've reversed this decision on https://github.com/tcorreabr/Parachute/issues/37, which is really sad because this would actually create a workflow that's currently impossible on KDE but GNOME people have learned to love, also sad because krunner can show open windows and go to those. On GNOME you can teach anyone, a small kid, or elderly relative, to use it, because 1 single key shortcut (meta key) will let you see windows, manage workspaces, and search for apps without them having to remember several places to click or multiple multi-key shortcuts. I thought Parachute was the one to take it home where qOverview and Kwinoverview started, but alas, everyone on here and many reddit threads waiting for a solution will look for a different project. It's obvious this issue has a lot more desire form the userbase than issue #37, but as the creator it's your decision.

**Comment by tcorreabr** [comment]
What I want to avoid is one key to activate krunner and another to filter windows. I want any alphabet key to activate an input field to search for windows. I'm thinking of a config option to work with krunner or the simple filter, what do you think?

As for implementing all GNOME's behavior on the subject, we have an important limitation with KWin scripts: the windows created by scripts overlap all other windows, including plasma panels. I'm not sure but maybe this kind of limitation can be solved by migrating from KWin script to KWin effect, or even a standalone app with dependency on KWin libs.

**Comment by koma111** [comment]
I think the config option is the way to go. Typing should either go to KRunner (Plasma Search) or to filtering windows, no extra key presses required that people need to memorize. The label could change accordingly from "Type to search" to "Type to filter".

**Comment by ikeofkc** [comment]
Great implementation. Where can we donate some money towards your next lunch?
