### ISSUE TITLE
Close Button Should be Right-Aligned

### ISSUE THREAD

**Issue by Modelmat** [tcorreabr/Parachute#53]
I believe that aligning the close button to the right side of the window would look nicer than have it just to the right of the text.

View now:
![view-now](https://user-images.githubusercontent.com/25718989/94755836-2c3e5080-03d9-11eb-9e4f-cec44325a6c5.png)

Right Aligned Views: (fully and aligned to window border) - unsure which looks nicer.
![view-alt-right-aligned](https://user-images.githubusercontent.com/25718989/94755838-2e081400-03d9-11eb-84d2-61b55e916454.png)
![view-right-aligned](https://user-images.githubusercontent.com/25718989/94755839-2ea0aa80-03d9-11eb-97cd-3cd7f129c641.png)

**Comment by luema** [comment]
I actually prefer it in the middle because it's easier to ignore. I don't use nor like seeing the close button, but I want to be able to see the window names and there's no avoiding the close button in that case. I think if the config file is adapted to allow for the disabling of the close button, it would be natural to allow for choosing the position of it as well if the choice is made to keep the button there.

**Comment by Modelmat** [comment]
What about following how KDE's present windows dialogue does it?
The close button only appears when you hover over a specific window.

(Also, I much prefer the look of the close button their rather than this bright red one).

**Comment by DenysMb** [comment]
I think that right aligned it's better. Not by personal taste only, but because follows the Plasma "guideline". All the close button in some overview or something is right aligned, not in the center.
