### ISSUE TITLE
Expose config in KCM UI

### ISSUE THREAD

**Issue by ericschdt** [tcorreabr/Parachute#87]
I have installed Parachute via git clone && make install, afterwards it appears in the Systemsettings' KWin scripts page. However, there one can only en- or disable or uninstall Parachute. It would be convenient if Parachute could also be configured there.

System: Manjaro

**Comment by koma111** [comment]
Check the README.md file (the [main page](https://github.com/tcorreabr/Parachute) of the project) for instructions. For your convenience, I copy the command here:
`mkdir -p ~/.local/share/kservices5
ln -s ~/.local/share/kwin/scripts/Parachute/metadata.desktop ~/.local/share/kservices5/Parachute.desktop
`
I assume you are familiar with the Linux command line, so you probably can figure out what this does. For the config dialog to work, this has to be done once, otherwise KDE doesn't recognize the config dialog. Note that this is not reset by updates, so you don't have to do it again when a new release of Parachute, Plasma, or any other software comes out.

@tcorreabr This can be closed.

**Comment by ericschdt** [comment]
> @tcorreabr This can be closed.
Not so fast, please.

It says
> If you have installed through Plasma's Get Hot New Stuff (Kde Store) you must execute the following commands on terminal to install the configuration dialog. You only need to do this once.

but I did _not_ install it that way as I said. If I'm not mistaken, these commands happens are executed with `make install` but I will check it again.

**Comment by ericschdt** [comment]
Never mind, something must have gone wrong. I removed all fractions and installed it again, works fine now. :)
